### ISSUE TITLE
DIO - Consulta no diário oficial - mobile

### ISSUE THREAD

**Issue by vizeke** [prodest/es-na-palma-da-mao-mobile#10]
@fredericoxa commented on [Tue Jun 28 2016](https://github.com/prodest/es-na-palma-da-mao/issues/9)

Consultar o diário oficial em um período e por palavra-chave.

**Comment by fredericoxa** [comment]
Inicialmente será implementado uma pesquisa onde o resultado será o link para o PDF que pode ser aberto por outro aplicativo no celular.
