### ISSUE TITLE
Estrela de Favorito do Onibus - Amarela ou Azul

### ISSUE THREAD

**Issue by rcolnago** [prodest/es-na-palma-da-mao-mobile#107]
Prezados,

Testei o recurso favoritar linha de ônibus... Acho que temos seguir a diretriz de cor do Material se aplicável... Ao invés de preto, usar Amarelo ou Azul.

Obrigado!

Abraços

Renzo

**Comment by hoisel** [comment]
@rcolnago, uma novo [ajuste](4c6f110c89d8adeac92da31cfa5e6ac2afc1a8a2) foi feito, para colocar no padrão visual de cores do aplicativo. Tanto dourado, quanto vermelho ou preto, além de não ter ficado visualmente bom, fugia ao padrão de cores do app. Assim optou-se pelo rosa, que tem sido usado no aplicativo para informações secundárias nas páginas, bem como para botões ( e a estrela é uma botão ).
