### ISSUE TITLE
calendar - Nome do mês desalinhado no IOS

### ISSUE THREAD

**Issue by hoisel** [prodest/es-na-palma-da-mao-mobile#184]
No ios, nome do mês aparece desalinhado, inclusive sendo cortado em dispositivos com resolução pequena.

![image](https://cloud.githubusercontent.com/assets/400244/19151270/27ed0372-8ba2-11e6-8af7-a6847dee4c61.png)

**Comment by vizeke** [comment]
No iOS é padrão o título do header abre centralizado por padrão. implementação do Ionic
