### ISSUE TITLE
Mensagem de erro quando dados da carteira estão com problema tá errada

### ISSUE THREAD

**Issue by TadeuTorres** [prodest/es-na-palma-da-mao-mobile#197]

**Comment by vizeke** [comment]
Tem como mandar um print?

**Comment by TadeuTorres** [comment]
![screenshot_2016-10-11-22-55-11](https://cloud.githubusercontent.com/assets/16275628/19294861/ac7126ce-9006-11e6-932e-d2a79bf02916.png)
