### ISSUE TITLE
"cadastre-se" com Google/Facebook não deveria exigir nova senha

### ISSUE THREAD

**Issue by josmardias** [prodest/es-na-palma-da-mao-mobile#202]
Primeiramente parabéns pela plataforma!

Minha sugestão em relação ao "cadastre-se":

Ao utilizar uma conta externa (Google/Facebook), não deveria ser exigido uma senha para a plataforma, uma vez que a idéia é utilizar a conta externa para futuros acessos.

Exemplo: https://bitbucket.org/account/signin/

**Comment by TadeuTorres** [comment]
@josmardias, avaliamos essa possibilidade. Só que pela nossa experiência, quase 20% dos usuários tem problema com a senha logo no começo e precisam recuperar de algum modo o acesso. (Sim, quase 20% perdem o acesso a conta externa...). Além disso tivemos uma quantidade expressiva de usuários tentando entrar com o CPF, mas com a senha da conta externa, em vez de clicar no botão do google ou do facebook...
Precisamos levar em consideração o perfil do usuário: A maior dificuldade nesse caso é casar a necessidade de simplificação para usar o sistema, com a segurança no acesso aos dados pessoais em um sistema com cadastro 100% digital.
Na prática, a senha "a mais", apesar de redundante, diminuiu o número de problemas.
