### ISSUE TITLE
Detalhes no cadastro.

### ISSUE THREAD

**Issue by lucianopf** [prodest/es-na-palma-da-mao-mobile#207]
Primeiramente parabéns pelo projeto sensacional!!

Vou listar aqui alguns pequenos probleminhas que reparei ao acessar o app:

- Ao clicar para se cadastrar e digitar o cpf seria melhor se o teclado exibido fosse apenas numérico.
- Durante o preenchimento do cadastro as vezes quando clico em algum input aparece os botões de zoom que acho que não deveria aparecer, e quando minimizo o teclado os botões permanecem lá tbm, conforme as imagens:
[Img1](https://www.dropbox.com/s/3uat8gg2tvntq4z/Screenshot_20161013-121616.png?dl=0),
[Img2](https://www.dropbox.com/s/49exry5o6rv1wcr/Screenshot_20161013-121624.png?dl=0).

**Comment by rcolnago** [comment]
Valeu pela colaboração @lucianopf !

**Comment by hoisel** [comment]
@lucianopf , essa tela de cadastro é temporária e em breve será melhorada. Por enquanto fazemos um aproveitamento da versão web do [acesso cidadão](https://acessocidadao.es.gov.br/Conta/VerificarCPF) De qualquer forma sua observação é muito válida e a correção já foi realizada.
