### ISSUE TITLE
Solicitação de acesso ao aplicativo

### ISSUE THREAD

**Issue by celsoagra** [prodest/es-na-palma-da-mao-mobile#212]
Gostaria de ter acesso a aplicação. É possível!?

**Comment by alvarollmenezes** [comment]
Estamos providenciando um ambiente de autenticação de testes e assim que estiver disponível disponibilizaremos o arquivo de settings que falta.

**Comment by celsoagra** [comment]
OK!
Obrigado pela ajuda

**Comment by celsoagra** [comment]
Desculpe pela demora na resposta a essa issue. Estamos iniciando um novo projeto utilizando a plataforma Ionic2.
Poderíamos criar um canal no Gitter para trocar um pouco o conhecimento das liguagens e frameworks. O que acha?

**Comment by hoisel** [comment]
Olá @celsoagra, agora já é possível acesso ao aplicativo! Te mandei msgs no gitter
