### ISSUE TITLE
style: Melhorar mensagens de commit

### ISSUE THREAD

**Issue by armand1m** [prodest/es-na-palma-da-mao-mobile#222]
Não sou ativo no projeto, mas analisando as mensagens de commit percebi que vocês tentam fazer uso do padrão de commit convencional para changelog, o mesmo usado pela equipe do angular por exemplo, mas que mesmo assim ainda continuam fazendo commits com mensagens fora do padrão.

Uma proposta de melhoria:
- Utilizar git hooks para validar se a mensagem está no padrão correto. É interessante usar um módulo como [git-hooks](https://www.npmjs.com/package/git-hooks) e o script de validação para o changelog convencional.
- Utilizar o módulo [commitizen](https://www.npmjs.com/package/commitizen) para fazer commits em vez do `git commit` comum.

**Comment by hoisel** [comment]
Legal mesmo a dica, @armand1m, vamos olhar. Alguns commits estão fora do padrão propositalmente pra não entrar no changelog!

**Comment by hoisel** [comment]
Implementado em 4fdca6b2037822ef634fcb8ece91e05283b492df e f9d238340f0c187c895dc66fc70f164e6136f94c.
