### ISSUE TITLE
Design do app

### ISSUE THREAD

**Issue by samverneck** [prodest/es-na-palma-da-mao-mobile#240]
Apresento o Bulma a vocês para o design do app, aqui está o site http://bulma.io/

Bulma é um framework CSS com diversos recursos, conta com sistema de grid css e recursos que lembram Bootstrap. Ele é baseado em Flexbox, uma especificação do CSS3...

Para saber mais sobre aqui vai um artigo: https://www.html5dev.com.br/blog/2015/05/14/css3-flex-box-tudo-o-que-voce-precisa-saber/

**Comment by samverneck** [comment]
https://material.uplabs.com/

**Comment by hoisel** [comment]
Olá @samverneck , já usamos o angular-material e o ionic para este propósito. Grato pela sugestão
