### ISSUE TITLE
incidente na iniciação o app

### ISSUE THREAD

**Issue by samverneck** [prodest/es-na-palma-da-mao-mobile#241]
o aplicativo não está iniciando conforme era antes, parece estar pesado causando a não iniciação do mesmo e fazendo com que eu não possa utiliza-lo.

**obs: minha versão do android é kit kat 4.4.4**

**Comment by hoisel** [comment]
Olá @samverneck , qual a versão do ESPM que você está usando?

**Comment by samverneck** [comment]
@hoisel não sei, pois o app não está inicializando no meu celular

**Comment by alvarollmenezes** [comment]
@samverneck 
Vou fechar a issue, pois acredito que tenha sido corrigida, qualquer coisa comenta aqui que eu reabro.

Valeu!
