### ISSUE TITLE
CETURB - Reportar reclamações

### ISSUE THREAD

**Issue by alvarollmenezes** [prodest/es-na-palma-da-mao-mobile#257]

**Comment by mikaelhadler** [comment]
Pessoal, rola uma descrição de como a GV bus receberia estas reclamações? Tá rolando alguma API que posso consultar e dar um start nessa thread?

**Comment by alvarollmenezes** [comment]
Bom dia @mikaelhadler,

Essa feature-request era relacionada ao envio de reclamações e sugestões que já estão disponíveis no app hoje.

A solução acabou sendo feita em outra api (https://github.com/prodest/api-demandas) que foi criada com a intenção de ser uma API genérica de demandas.

Vou até atualizar essa feature que foi encerrada em outro lugar.

**Comment by alvarollmenezes** [comment]
Apenas complementando, atualmente a Ceturb recebe as reclamações registradas pela API no seu canal de fale conosco.
