### ISSUE TITLE
Possibilitar consulta de linhas a perfil visitante

### ISSUE THREAD

**Issue by pcthiebaut** [prodest/es-na-palma-da-mao-mobile#265]
Verifiquei que a consulta a linhas de ônibus somente é permitida a usuários logados. Essa exigência é desnecessária e invade a privacidade do usuário. Solicito que somente sejam mantidas com exigência de log as funcionalidades que exijam a identificação do usuário. Todas as outras funcionalidades devem ser acessíveis sem a identificação de seus demandantes. Obrigado.

**Comment by alvarollmenezes** [comment]
Obrigado pela sua sugestão.
Ontem disponibilizamos, na versão 3.6.0 para o android, a sua solicitação. Logo estará disponível para iOS.

Por favor, atualize sua versão e qualquer coisa comente aqui.

Atenciosamente,
Álvaro

**Comment by alvarollmenezes** [comment]
Vou fechar a issue, pois acredito que sua demanda tenha sido atendida.

Fique a vontade para comentar aqui e reabrimos sua issue.

Obrigado.
