### ISSUE TITLE
Carteira de Motorista 

### ISSUE THREAD

**Issue by mouraee** [prodest/es-na-palma-da-mao-mobile#266]
Olá.  A aplicação está com algum problema para consultar a carteira de motorista. Tinha a minha cadastrada e derrepente passou a não mais encontrar.

**Comment by vizeke** [comment]
@mouraee lançamos um patch nesse momento pra corrigir esse problema. A atualização já está no google play. Favor atualizar o aplicativo para versão 3.6.1 que estará funcionando.
