### ISSUE TITLE
Travamento ao acessar "Situação CNH"

### ISSUE THREAD

**Issue by RaphaelGNunes** [prodest/es-na-palma-da-mao-mobile#282]
Sempre que tento acessar o ítem do menu "Detran" > "Situação CNH" o aplicativo trava.

**Comment by alvarollmenezes** [comment]
Iremos avaliar o que pode estar acontecendo e entraremos em contato novamente.

Obrigado pelo feedback.

**Comment by mouraee** [comment]
As informações sobre a CNH não aparecem mais, apenas a tela em branco.

**Comment by alvarollmenezes** [comment]
@mouraee Obrigado pelo contato, observamos o bug na tela de situação de CNH e estamos corrigindo.

Aviso assim que corrigido aqui na issue.

**Comment by alvarollmenezes** [comment]
Boa tarde,

Acredito que a situação esteja corrigida.

Fecharei a issue, caso algum de vocês perceba que o erro persiste favor comentar que reabrirei a issue.

Obrigado,
Álvaro.
