### ISSUE TITLE
Reporta estar offline tendo conexão

### ISSUE THREAD

**Issue by marcoaureliocardoso** [prodest/es-na-palma-da-mao-mobile#283]
Reporta estar offline tendo conexão.

![screenshot 22 de agosto de 2017 14-15](https://user-images.githubusercontent.com/9138786/29578792-e592cff6-8746-11e7-951e-02d38c3b4437.png)

**Comment by samverneck** [comment]
Aproveitando essa issue uma opinião minha seria trabalhar no ESPM para que funcione offline

**Comment by alvarollmenezes** [comment]
@marcoaureliocardoso 
Estamos cientes dessa situação, com a última atualização do google alguns de nossos serviços ficaram indisponíveis, estamos correndo para que tudo esteja disponível novamente o mais rápido possível. Obrigado pelo contato.

@samverneck 
Já está previsto na fase de migração o estudo e possível desenvolvimento do app como um PWA, para que funcione offline, o que não é a situação reportada nesse momento. Obrigado.

**Comment by alvarollmenezes** [comment]
Esta situação foi corrigida ontem pela equipe de suporte da Prodest.

Vou fechar como solucionado, porem peço que testem e retornem com feedback, caso necessário reabriremos o incidente.

;)
