### ISSUE TITLE
Implementar serviço de push notification

### ISSUE THREAD

**Issue by alvarollmenezes** [prodest/es-na-palma-da-mao-mobile#57]

**Comment by vizeke** [comment]
Foi utilizado o plugin https://github.com/phonegap/phonegap-plugin-push para criação do serviço de notificação no cordova.
Mas para que a notificação pudesse ser tratada de acordo com a localização do dispositivo foi necessário  estender o plugin. Pra isso fizemos um fork do projeto em https://github.com/prodest/phonegap-plugin-push e adicionamos a funcionalidade.
Agora o plugin de notificação deve ser instalado a partir do repositório da Prodest.
