### ISSUE TITLE
Consulta do DIO está fora de ordem

### ISSUE THREAD

**Issue by alvarollmenezes** [prodest/es-na-palma-da-mao-mobile#60]
Mesmo a api retornando o resultado ordenado por data o dispositivo retornou fora de ordem a consulta "Alvaro Luiz lago de menezes" (com aspas)

https://api.es.gov.br/dio/search?query=%22Alvaro%20luiz%20lago%20de%20menezes%22

**Comment by hoisel** [comment]
A ordenação já está feita corretamente na tela. A API do DIO retorna os resultados ordenados somente por data(quando solicitado). A tela adiciona uma ordenação adicional aos resultados: dentro de uma mesma data, ordena por página de forma crescente. 

Resumindo: o retorno da API que não ordena simultaneamente por data (desc) e página (asc). Essa ordenação é feita na tela.
