### ISSUE TITLE
CETURB - Pesquisa de ônibus por ruas

### ISSUE THREAD

**Issue by RobertoMarconi** [prodest/es-na-palma-da-mao-mobile#66]
Ao pesquisar linhas de ônibus, seria interessante que o usuário pudesse encontrar quais ônibus passam em determinada localidade. 
Ex: quero saber todos os ônibus que passam na avenida vitória. Hoje só é possível procurar pelo nome e número da linha, o que não ajuda muito quando o nome pode ser T Vila Velha x T Itacibá, por exemplo.

**Comment by alvarollmenezes** [comment]
Com os dados atuais da API da Ceturb não é possível implementar essa funcionalidade.
