### ISSUE TITLE
Dio - Pesquisa por mais de uma palavra não funciona

### ISSUE THREAD

**Issue by RobertoMarconi** [prodest/es-na-palma-da-mao-mobile#67]
Tentei pesquisar "Roberto Marconi" e não funcionou, destacando resultados para apenas "Roberto".
Se colocar "Roberto Marconi" entre aspas não deveria trazer somente o caso de ocorrência das duas palavras uma após a outra?

**Comment by vizeke** [comment]
Essa alteração deve ser feita na API do DIO, que nós não temos acesso. Favor abrir um chamado no DIO. ;)
