### ISSUE TITLE
Horário de ônibus

### ISSUE THREAD

**Issue by liviozanol** [prodest/es-na-palma-da-mao-mobile#87]
Horas de itinerante ficam "cinza" em horários posteriores ao atual mesmo em outros dias

**Comment by vizeke** [comment]
Não consegui reproduzir o problema. Tem como detalhar melhor? Qual filtro ou qual linha vc testou?

**Comment by liviozanol** [comment]
Segue imagem... Pode ser que eu tenha entendido errado e era para ser assim
mesmo.

Eu achei q ia exibir o dia atual com os horários passados em cinza, e
abaixo os outros dias com todos os horários em preto, mesmo os passados.

Vendo hoje acho que o design é realmente manter todos os horários em cinza,
independentemente do dia.

Nesse caso, se for isso mesmo, não é uma issue, peço desculpas.

Em 27 de ago de 2016 9:35 AM, "Vinícius Salomão" <notifications@github.com>
escreveu:

**Comment by alvarollmenezes** [comment]
Pela complexidade que envolve descobrir os dias "atípicos" optamos por clarear os horários de todos os grupos de dias.

Cria issue mesmo, é isso que a gente espera.
