### ISSUE TITLE
Salvar número da CNH no login caso exista

### ISSUE THREAD

**Issue by vizeke** [prodest/es-na-palma-da-mao-mobile#92]
Depois de efetuar o login o número da CNH que vem do acesso cidadão não está sendo salvo corretamente no localstorage.

**Comment by hoisel** [comment]
### Causa 
Problema ocorrido devido ao fato de que o [evento](https://github.com/prodest/es-na-palma-da-mao-mobile/commit/bb55abce634ed3e920d882add3a6187f3e66e57c#diff-d63c253674cb5cef6c635bdad01b2187L127) disparado por *notifyng-service* não estava sendo [assinado](https://github.com/prodest/es-na-palma-da-mao-mobile/commit/bb55abce634ed3e920d882add3a6187f3e66e57c#diff-a9b8d03f33f4590e6ffa6894e4bf65beL22) em *DetranStorage*, visto que o mesmo ainda não estava carregado na app no momento do disparo do evento(lazy-loading).

### Solução
Os dados(claims) do usuário, incluindo a carteira já são salvos no local-storage no momento do login. Com isso [DetranStorage](https://github.com/prodest/es-na-palma-da-mao-mobile/blob/bb55abce634ed3e920d882add3a6187f3e66e57c/src/components/detran/shared/detran-storage.service.ts) passou a atuar também como uma facade pros dados do usuário - no contexto do DETRAN - salvos no local-storage.

Assim [notifying-service](https://github.com/prodest/es-na-palma-da-mao-mobile/blob/5825bdf7382b54c8552a40f3ceafa3ebccc3fbc1/src/components/shared/notification/notifying-service.ts) pôde ser removido pois não funcionaria bem com a arquitetura *lazy-loading*, pois não poderia garantir que os componentes interessados em assinar um evento estivessem carregados no momento que tais eventos fossem disparados.

Resolvido nos commits e06ab99322176f6ae891712a49da2935f4f260f4 e bb55abce634ed3e920d882add3a6187f3e66e57c
