### ISSUE TITLE
Verificar necessidade da opção Dashboard na versão inicial

### ISSUE THREAD

**Issue by liviozanol** [prodest/es-na-palma-da-mao-mobile#94]
Avaliar se é necessário deixar a opção Dashboard (menu) na primeira versão do aplicativo.

Sugiro que na primeira versão do app seja retirada esta opção, só colocando-a quando houver a possibilidade de customização pelo usuário das informações que o mesmo gostaria que estivessem dispostas nesta seção.

**Comment by hoisel** [comment]
@rcolnago, que acha?

**Comment by rcolnago** [comment]
@hoisel e @vizeke, penso que a ideia do @liviozanol é pertinente. 
Acho que o termo DASHBOARD podemos deixar para quando estivermos com menus configuráveis de forma que o cidadão consiga customizar e favoritar recursos na home. 
Outra coisa... O que acham de pensarmos uma landing page?
O que acham?

**Comment by hoisel** [comment]
Item de menu foi renomeado de 'dashboard' para 'principal'. Solução temporária enquanto não existe um dashboard real.
