### ISSUE TITLE
Consulta de multas por veículo

### ISSUE THREAD

**Issue by rmalbert** [prodest/es-na-palma-da-mao-mobile#95]
O aplicativo não emite mensagem quando tenta consultar as multas de um veículo cadastrado com placa ou renavam errados.

**Comment by vizeke** [comment]
relacionado com  prodest/es-na-palma-da-mao-backend#23

**Comment by hoisel** [comment]
Resolvido em 84173ef201d5dccca885ce5ed45ba7f802b4719e
