### ISSUE TITLE
CETURB - Local de itinerário de ônibus com plotagem errada no mapa

### ISSUE THREAD

**Issue by rmalbert** [prodest/es-na-palma-da-mao-mobile#96]
Certos locais de itinerários de ônibus não estão aparecendo corretamente no mapa. Ex.: Av. São Paulo (em Vila Velha) está caindo em São Paulo.

**Comment by hoisel** [comment]
Como a API da ceturb não fornece coordenadadas geográficas para consulta, foi adicionada ",ES" ao parametro de consulta passado ao gmaps, visando reduzir o contexto da busca ao Espírito Santo.
